// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function Download(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function List(arg1:string):Promise<Array<string>>;

export function OpenAndUploadFile():Promise<string>;

export function StopDownload():Promise<void>;

export function Upload(arg1:string,arg2:string):Promise<void>;
