// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function OpenAndUploadFile() {
  return window['go']['main']['App']['OpenAndUploadFile']();
}

export function StopDownload() {
  return window['go']['main']['App']['StopDownload']();
}

export function Upload(arg1, arg2) {
  return window['go']['main']['App']['Upload'](arg1, arg2);
}
