// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['FTPClient']['Connect'](arg1, arg2, arg3);
}

export function CreateFolder(arg1) {
  return window['go']['main']['FTPClient']['CreateFolder'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['FTPClient']['Delete'](arg1);
}

export function Disconnect() {
  return window['go']['main']['FTPClient']['Disconnect']();
}

export function Download(arg1, arg2) {
  return window['go']['main']['FTPClient']['Download'](arg1, arg2);
}

export function List(arg1) {
  return window['go']['main']['FTPClient']['List'](arg1);
}

export function Upload(arg1, arg2) {
  return window['go']['main']['FTPClient']['Upload'](arg1, arg2);
}
