// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['FTPClient']['Close']();
}

export function Dele(arg1, arg2) {
  return window['go']['main']['FTPClient']['Dele'](arg1, arg2);
}

export function Dial(arg1) {
  return window['go']['main']['FTPClient']['Dial'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['FTPClient']['ListFiles'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['FTPClient']['Login'](arg1, arg2);
}

export function MakeDir(arg1) {
  return window['go']['main']['FTPClient']['MakeDir'](arg1);
}

export function REST_RETR(arg1, arg2, arg3, arg4) {
  return window['go']['main']['FTPClient']['REST_RETR'](arg1, arg2, arg3, arg4);
}

export function RETR(arg1, arg2) {
  return window['go']['main']['FTPClient']['RETR'](arg1, arg2);
}

export function STOR(arg1, arg2) {
  return window['go']['main']['FTPClient']['STOR'](arg1, arg2);
}

export function SendCommand(arg1) {
  return window['go']['main']['FTPClient']['SendCommand'](arg1);
}

export function SetAsciiMode() {
  return window['go']['main']['FTPClient']['SetAsciiMode']();
}

export function SetBinaryMode() {
  return window['go']['main']['FTPClient']['SetBinaryMode']();
}
